apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: node:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
