apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node-service
  namespace: default
spec:
  selector:
    app: node
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort